
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqltrdeswmczkhliqjle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxbHRyZGVzd21jemtobGlxamxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MzgwMjksImV4cCI6MjA2MzUxNDAyOX0.iJtu7N6ZzCr_TM4ZXpDlOVFdhx7JE5sYas1v8URcr_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Function to clean up auth state (useful for logout/errors)
export const cleanupAuthState = () => {
  // Remove all Supabase auth keys from localStorage
  Object.keys(localStorage).forEach((key) => {
    if (key.startsWith('supabase.auth.') || key.includes('sb-')) {
      localStorage.removeItem(key);
    }
  });
};

// Helper function to safely log out
export const safeSignOut = async () => {
  try {
    await supabase.auth.signOut({ scope: 'global' });
  } catch (err) {
    console.error('Error signing out:', err);
  }
  cleanupAuthState();
};
